### ISSUE TITLE
smooth(ep, ...) is not correct Modelica

### ISSUE THREAD

**Issue by adrpo** [MarekMatejak/Physiolibrary#11]
Modelica specification says for smooth(p, expr):
The argument p should be a scalar integer parameter expression.
In this case is not as "ep" is defined as: Types.Pressure ep; which is not integer and not a parameter!

https://github.com/MarekMatejak/Physiolibrary/blob/master/Physiolibrary/Hydraulic.mo#L1288

**Comment by MarekMatejak** [comment]
The pressure in elestic compartment should be only continuous function (zero as first parameter of smooth), so more orders of continuous derivations are not needed there.
Thanx
m.
