### ISSUE TITLE
Library award

### ISSUE THREAD

**Issue by tbeu** [MarekMatejak/Physiolibrary#21]
I noticed that Physiolibrary applied for the award at https://modelica.org/events/modelica2014/proceedings/html/sessions/session_libraries.html. Do you know the winning three libs? Unfortunately I cannot find any public record for it. Thanks.

**Comment by MarekMatejak** [comment]
Physiolibrary was first, ThermoCycle was second. I am not sure about the third place.

**Comment by tbeu** [comment]
Thanks.
