### ISSUE TITLE
Invalid use of enumeration literal for Integer-indexed array

### ISSUE THREAD

**Issue by maltelenz** [MarekMatejak/Physiolibrary#37]
Here:

https://github.com/MarekMatejak/Physiolibrary/blob/b29e62d9be6cd4ed6c4ecfb56349be7e355c905b/Physiolibrary/Fluid.mo#L3062

An enumeration literal is used to index in `lungs.substances`.

However, `lungs.substances` is indexed using an `Integer`:

https://github.com/MarekMatejak/Physiolibrary/blob/b29e62d9be6cd4ed6c4ecfb56349be7e355c905b/Physiolibrary/Fluid.mo#L702

I believe this is not legal Modelica. The [specification says](https://specification.modelica.org/master/arrays.html#boolean-or-enumeration-indices):

> The type of the index should correspond to the type used for declaring the dimension of the array.

**Comment by MarekMatejak** [comment]
Hi Malte,
thank you for the feedback. I will fix it on Monday. 
Kind Regards
Marek
