### ISSUE TITLE
Illegal inheritance in Physiolibrary\Icons.mo

### ISSUE THREAD

**Issue by tbeu** [MarekMatejak/Physiolibrary#8]
The Modelica class of Physiolibrary.Icons.Library (class) and its base class Modelica.Icons.Package (package) are not compatible.
The Modelica class of Physiolibrary.Icons.BaseLib (class) and its base class Modelica.Icons.Package (package) are not compatible.

**Comment by mesamis** [comment]
Yes, thank you.

**Comment by MarekMatejak** [comment]
Yes, thank you.
